### ISSUE TITLE
HTML5 Video autoplay test does not give reliable results

### ISSUE THREAD

**Issue by kristerkari** [Modernizr/Modernizr#1095]
I created a custom build of Modernizr with latest `video`, `video/autoplay` and `video/loop` tests. When listening to the async autoplay test with `.on` I have noticed that in Chrome 30 stable on OS X the test sometimes returns true and sometimes false. Firefox 26 beta 4 on OS X returns false every time.

As I was trying to understand what is going on, I added a 200ms timeout to testAutoplay function. Delaying the `elem.currentTime !== 0` test by 200ms made the test pass on every page refresh I did in Chrome and FF.

I tried updating the `videoautoplay` test with code from this PR https://github.com/Modernizr/Modernizr/pull/1018 and running the test after that, but looks like that does not help.

Is there a better way of fixing this, since adding a timeout to delay the test does not sound very optimal?

Oh yeah, here is my test html file:
```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <script src="modernizr-build.js"></script>
</head>
<body>
<script>
    Modernizr.on('videoautoplay', function (hasAutoplay) {
        console.log(hasAutoplay);
    });
</script>
</body>
</html>
```

**Comment by bjornbjorn** [comment]
Still an issue. Safari OSX Version 8.0.8 (10600.8.9) sometimes shows up with "no-autoplay" and sometimes with "autoplay".

**Comment by meibegger** [comment]
In Chrome Version 46.0.2490.71 (64-bit), OSX 10.10.5 i only get autoplay=true when i load the page for the first time. So on reload i get autoplay=false; after clearing the browser-cache i again get autoplay=true once.
Neither increasing the waitTime nor the timeout helped to solve the problem.

**Comment by benedfit** [comment]
+1

**Comment by devpascoe** [comment]
Same here, test is true if first load, reload nope. Clear cache, refresh = yes

**Comment by irishdan** [comment]
Same as above. The test only passes on the first page load. This issue should be reopened

**Comment by geekuillaume** [comment]
No news on this and I have the same problem with Chrome. Could this issue be reopened?

**Comment by linusrendahl** [comment]
I can also confirm that it works while cache is disabled (otherwise not, obviously).

**Comment by pirm-in** [comment]
+1

**Comment by andymantell** [comment]
Am experiencing the same here in Chrome 47.0.2526.80 on Windows. On first load with an empty cache it reports true. All subsequent loads with a primed cache report false.

**Comment by damirkotoric** [comment]
Same here on a Mac running Chrome 47.0.2526.106 (64-bit)

**Comment by damirkotoric** [comment]
I wasn't able to figure out a fix for this bug, but as a temporary workaround I targeted the .no-touchevents Modernizr class instead. Hoping to see this fixed eventually though as the workaround isn't as reliable.

**Comment by ryanseddon** [comment]
@damirkotoric We've fixed the issue in master we'll still need to cut a release. Check out #1795.

**Comment by damirkotoric** [comment]
:+1:

**Comment by mitchward** [comment]
This issue still persists for me in Chrome 47 on OSX. Generated the build just now and after a quick look at the generated code, it appears to have the fix referenced in #1795 applied, but still having issues. As mentioned above, increasing the timeout increased success rate, but still get the odd false-negative.

**Comment by ryanseddon** [comment]
No we haven't cut a release yet so it's not available in the builder. If you build one from master and try it you won't get the issue in Chrome.

**Comment by eladvider** [comment]
I build from the master and still get the bug in chrome 47, its reproduce after some refresh

**Comment by ryanseddon** [comment]
Created a test case from master and am not getting any issues in osx chrome 47. http://output.jsbin.com/xenabiqoga/1/quiet

Background should be red if it fails I have gotten the green background on 10+ refreshes.

**Comment by bjornbjorn** [comment]
I get neither green nor red background on the first load of that page in Chrome 47.0.2526.106 (64-bit) OSX. Same result in the iPad simulator; first load - white background.

After the first load it seems to work fine (to reproduce use inkognito mode).

**Comment by meibegger** [comment]
On my OSX Yosemite, Chrome 47.0.2526.106 (64-bit) i get a white background with cleared cache, then a green background on reload and after that it's red

**Comment by mitchward** [comment]
Exactly the same setup as above here, with same results.
Also, same results on previous test case that was made: https://codepen.io/anon/pen/QyWQjQ

**Comment by khromov** [comment]
Any news on this?

**Comment by eladvider** [comment]
HI,
in the meantime i create the following script to check if auto play is supported 
checked on chrome,IE, IOS, Andorid tablet and FF

var vid = document.createElement('video');
        vid.autoplay = true;
        vid.src = 'some mp4 vido url'; // insert src of real video 
        vid.load();
        vid.style.display = "none";
        vid.notRunning = true;
        vid.play();
        vid.onplay = function () {
            this.notRunning = false;
        }; 
        vid.oncanplay = function () {
            setTimeout(function () {
                if (vid.notRunning)
                    fallback();
                document.body.removeChild(vid);
            }, 0);
      
        };  
        document.body.appendChild(vid); 

Hope its will help

**Comment by ryanseddon** [comment]
Seems all browsers but safari are using the ogg base64 video and once the base64 contents have been cached it gets weird?

![weird-autoplay](https://cloud.githubusercontent.com/assets/143402/12408957/b79daa3c-beb9-11e5-8292-61b43d6ea5f4.gif)

I made the [test](https://jsbin.com/fohuji/edit?html,js,output) super obvious what it's doing by using a test ogv video and showing it in the page rather than hiding and then removing.

**Comment by benjaminallison** [comment]
Chrome 47.0.2526.111 on Yosemite. Clear cache, returns true. Reload, returns false.

**Comment by furiousjason** [comment]
In Safari 8.0 (10600.1.25.1) on Yosemite (10.10.1), videoautoplay returns false every time. I can't seem to find a bug report about this issue specifically, but this seems like the most relevant thread.

**Comment by ryanseddon** [comment]
@furiousjason what about with the above [test case](https://output.jsbin.com/siwijafovi/quiet)?

**Comment by furiousjason** [comment]
Hi,

Thanks for getting back to me-

I've actually had to upgrade the computer in question (it's a mid 2010 mac mini) and even on El Capitan (10.11.3) and Safari 9.0.3, the test case seems not to work:

![screen shot 2016-03-16 at 13 00 55 jpg](https://cloud.githubusercontent.com/assets/1356797/13813233/5e2629e8-eb78-11e5-9326-596ac651d038.jpg)

Even on Chrome on this Mac, it returned false twice randomly in the 8 times I looked at it, but at least the video plays there.

**Comment by ryanseddon** [comment]
Yeah this is a tough one seems it doesn't like the base64 encoded video once it's cached. 

cc @paulirish you know any browser peeps at apple or in the chrome team who would know more on why this happens?

**Comment by patrickkettner** [comment]
don't have the ability to test, but what if we added a querystring with math.random?

**Comment by ryanseddon** [comment]
You can't add query strings to a base64 encoded string, I thought to do the same thing.

**Comment by mfairchild365** [comment]
I can't reproduce the test case by @ryanseddon on my Mac with chrome 50.  The video always appears to be loaded "from cache" even when cache is disabled. My guess is that simply means that the video was loaded via the base64 string (no network requests). This might have also been fixed in a recent chrome update? I also could not reproduce the test in safari.

That being said, I have seen this issue. Sometimes the autoplay will be detected accurately, and seemingly at random it fails. My guess is that it is more of a timing issue than a caching issue. The heavier the page, the less reliable the test seems to be. Perhaps some pages simply are not ready after 300ms? I've opened a PR to help address this issue. https://github.com/Modernizr/Modernizr/pull/1963

**Comment by ryanseddon** [comment]
[crbug#572628](https://bugs.chromium.org/p/chromium/issues/detail?id=572628) seems related, 50 has fixed it.

**Comment by jimmywarting** [comment]
Best way to detect: https://googlechrome.github.io/samples/play-return-promise/index.html

**Comment by jimmywarting** [comment]
Best way to detect if autoplay is supported: https://googlechrome.github.io/samples/play-return-promise/index.html

**Comment by monospaced** [comment]
👍

**Comment by simoncoudeville** [comment]
I have noticed that the class `videoautoplay` is always added. The javascript check `if (Modernizr.videoautoplay)` randomly fails.

**Comment by emilio-martinez** [comment]
@jimmywarting `HTMLMediaElement.prototype.play` probably does not return a `Promise` reliably across all browsers, especially since IE doesn't support it at all until Edge.

**Comment by emilio-martinez** [comment]
@ryanseddon would such a thing as appending a random set of chars compliant with the base64 encoding work? I'm not sure how feasible that is, but it would work in a similar manner as the query string; the difficulty would be to make the encoded value always valid

**Comment by sarukuku** [comment]
There's been race condition issues with this test as long as I can remember...

**Comment by sarukuku** [comment]
New browsers can these days autoplay video [even on mobile](https://webkit.org/blog/6784/new-video-policies-for-ios/). As testing the autoplay is a pain in the ass to do reliably by loading a video and trying to check if it has played or not how about lifting the limit of what "cuts the mustard" and relying on the return of Promise from the play() method instead of actually trying to determine if the video is playing?

I understand that this might be not the way this test wants to go but I'll just drop my current demo solution [here](https://jsbin.com/pixokul/edit?html,js,output). Maybe someone will find it useful when googling for this. It swaps the video with a fallback image if the play() method doesn't return a Promise. Tested and works on new and bit older iOS, Android and desktop browsers.

**Comment by jimmywarting** [comment]
Thanks @sarukuku, I just learned that there is a `playsinline` attribute for iOS now

**Comment by paulorely** [comment]
The solution presented by @sarukuku is great, but it falls short in browsers that don't support Promises but **do** support video autoplay (notably IE 9–11).

His approach inspired me to explore another solution, which was succesfully tested on:

* IE 8–11, Edge (Windows);
* Chrome, Firefox (Windows, macOS, iOS, Android);
* Safari (macOS, iOS);
* Samsung Browser (Android).

```javascript
var supports_video_autoplay = function(callback) {
  
  if (typeof callback !== "function") return false;
  
  var v = document.createElement("video");
  v.paused = true;
  var p = "play" in v && v.play();
  
  callback(!v.paused || ("Promise" in window && p instanceof Promise));
  
};
```
A Promise return check is necessary, otherwise Chrome on Android returns a false negative.

Usage:

```javascript
supports_video_autoplay(function(supported) {
  if (supported) {
    // video autoplay supported!
  } else {
    // no video autoplay support :(
  }
});
```

**Comment by sarukuku** [comment]
@paulorely Excellent work! I've updated the [example](https://jsbin.com/rabadaloge/1/edit?html,js,console,output) to use your method. It has the opinionated image replacement fallback. I also tested the updated example with various old & new desktop & mobile browsers and it seems to perform very well (= doesn't work on Nokia Lumia & Androind <= 4.0).

I'll create a pull request of this for Modernizr.

**Comment by Colir** [comment]
For IOS don't forget to add "playsinline" attribute to the video tag with @paulorely solution.

**Comment by herschel666** [comment]
The test checking for the `play`-function to return a `Promise` gives a false positive on iOS. To get a valid result the resolving/rejection has to be checked, too.

```js
var supports_video_autoplay = function(callback) {
  var cb = typeof callback === "function" ? callback : function () {};
  var v = document.createElement("video");
  v.paused = true;
  
  if (!('play' in v)) {
    cb(false);
    return;
  }

  var p = v.play();

  if ('Promise' in window && p instanceof Promise) {
    p.then(
      function () {
        cb(true);
      },
      function () {
        cb(false);
      }
    );
    return;
  }
  
  cb(!v.paused);
};
```

**Comment by leendertvb** [comment]
@paulorely How can your code be only 4 lines and the current Modernizr approach (v3.5.0) is about 11KB of code to do the same? I see the Modernizr script has included 2 actual videos in the code, but without that, it is still pretty long compared to your code.

How reliable is your code? Can I safely use yours in a production website?

Thanks!

**Comment by paulorely** [comment]
I have extended the test in order to check for muted and unmuted video autoplay support. Interestingly, if you combine `video` and `audio` autoplay tests, you get reliable results (as far as I've tested).

```
var supports_video_autoplay = function(callback) {
  
  var v = document.createElement("video");
  v.paused = true;
  var p = "play" in v && v.play();
  
  var a = document.createElement("audio");
  a.paused = true;
  "play" in a && a.play();
  
  var vr = !v.paused || "Promise" in window && p instanceof Promise,
      ar = !a.paused;
  
  var r = "none";
  if (vr && !ar) r = "muted";
  else if (vr && ar) r = "full";
  
  callback(r);

};
```

Usage:
```
supports_video_autoplay(function(supported) {
  
  var el_result = document.getElementById("result"),
      el_html = document.documentElement;
  
  if (supported == "full") {
    // full video autoplay supported (muted and unmuted)
    el_result.innerHTML = "Full video autoplay support detected!";
    el_html.style.backgroundColor = "#0c0";
  }
  else if (supported == "muted") {
    // only muted video autoplay support
    el_result.innerHTML = "Video autoplay support detected (muted only)";
    el_html.style.backgroundColor = "#d90";
  }
  else if (supported == "none") {
    // no video autoplay support at all
    el_result.innerHTML = "Video autoplay support not detected :(";
    el_html.style.backgroundColor = "#900";
  }
  
});
```

Live test: https://codepen.io/paulorely/pen/Wdboem

**Comment by cavemon** [comment]
@paulorely thank you for this.  This seems to work well, although I am getting a console error in Desktop Safari: 

`Unhandled Promise Rejection: NotAllowedError (DOM Exception 35): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`

Is there someone to get rid of this error?

**Comment by gmathis** [comment]
This test gives a false positive for muted video autoplay when all autoplay is prohibited by the browser (e.g. Safari's "Never Auto-Play" setting).
It assumes that browsers that return a `Promise` from `play()` always allow muted video to autoplay.

Unfortunately, I think it's probably necessary to include actual video data (and ensure visible in viewport / `playsinline`), and listen for promise resolution (autoplay success) or rejection with `e.name ="NotAllowedError"` (autoplay failure). The latter will also prevent the console spam @cavemon mentioned.

**Comment by handyaner** [comment]
@sarukuku i tested your code https://jsbin.com/rabadaloge/1/edit?html,js,console,output
But it doesn't autoplay on an android with chrome 65.

**Comment by sarukuku** [comment]
@handyaner yep, there are still issues with the test that does not involve playing an actual video file. I've had this on my todo list for about a year now but haven't yet found time to look at it properly again. I'll probably focus on this when I need it next myself. So feel free to improve on others work in this thread 😄

**Comment by CaelanStewart** [comment]
@paulorely, on Chrome 69, this code...

```
var v = document.createElement("video");
v.paused = true;
```
...throws the following exception...

```
Uncaught TypeError: Cannot assign to read only property 'paused' of object '#<HTMLVideoElement>'
```

And hence, the callback is not executed.

**Comment by CaelanStewart** [comment]
Just thought I'd add:

For my case (a home page hero video), I just checked if the video is playing 5 times over the space of 1s (and hiding the video and replacing with static image if it isn't playing at any point) which seems to work quite reliably. Android autoplays, but iOS does not (with no discernible flash of the video, either).

**Comment by avpavp** [comment]
> @paulorely, on Chrome 69, this code...
> 
> ```
> var v = document.createElement("video");
> v.paused = true;
> ```
> ...throws the following exception...
> 
> ```
> Uncaught TypeError: Cannot assign to read only property 'paused' of object '#<HTMLVideoElement>'
> ```
> And hence, the callback is not executed.
> 
> Is there no reliable solution to this, yet?

Seems to work ok for me on Chrome 69.0.3497.100 (Official Build) (64-bit) Windows

**Comment by rejas** [comment]
Thx for the hint @avpavp indeed the specs only mention a function, not an object: https://www.w3schools.com/tags/av_met_pause.asp
@CaelanStewart is that a thing that might help you?

**Comment by rejas** [comment]
hi @rezaamya which version of modernizr are you using? because that code you posted is not in our current codebase...

**Comment by rezaamya** [comment]
Hi @rejas, Thanks for your reply. I am not using any version of modernizr!. I just have used the snippet code that @paulorely mentioned 2 years ago.

**Comment by taseenb** [comment]
Maybe someone already pointed to this article:
**Autoplay Policy Changes**
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

Basically for the detection to work, the video:
- Must be visible (no display:none, visibility:hidden, less than opacity:1)
- Minimum 200x140 px
- MUST BE MUTED! `elem.setAttribute('muted', '')` 

This way the detection works.

To hide the video I guess it would be possible to create a div and place it above it, until the detection is completed.

**Comment by xdhmoore** [comment]
I think there are 2 tests that could be done:
1) to determine if the `<video>` (or `<audio>`) tag is supported.
2) to determine if the element is playable due to media engagement scoring.

You can detect #2 by trying to `play()` something and looking to see if the promise is rejected with a `NotAllowedError`.
