### ISSUE TITLE
Modernizr errors in wet-boew

### ISSUE THREAD

**Issue by sulemanmirza** [Modernizr/Modernizr#1598]
Hi, I am using wet-boew.js in my web application, I am encountering an error in wet-boew.js which is related to Modernizr.AddTest function for mathml, I even added the non-core detects and checked mathml before downloading, only now I get the error in both wet-boew and modernizr. Please let me know.
![image](https://cloud.githubusercontent.com/assets/1385300/7705955/c2d5e9a8-fe04-11e4-89f3-5a33c60536b3.png)

![image](https://cloud.githubusercontent.com/assets/1385300/7705981/dfde7eb6-fe04-11e4-8a56-9b91953918ab.png)

**Comment by patrickkettner** [comment]
Hey @sulemanmirza!

You are using the older 2.X verison of the build. This issue has been fixed in 3.X. You can generate a new build on http://new.modernizr.com/download

**Comment by sulemanmirza** [comment]
Yes I was using the older 2.8.3 version and issue got fixed when I updated to the 3.00 Alpha 3. But the error is still their in wet-boew. Thanks for your help, I think that source is still using the old version.
Thanks

**Comment by patrickkettner** [comment]
cheers!
